enum UserType {
  SUDO
  USER
}

type ResponseCreateUser {
  status: String!
  error: String
}

type User {
  user_id: ID!
  login: String!
  password: String!
  # Define a regra do usuario, usado mais a frente para diferir o acesso a recursos do app
  #Usuario pode ser do tipo { SUDO= acesso total, USER= acesso limitado a sua fazenda}
  userType: UserType!
}
