# Define a regra do usuario, usado mais a frente para diferir o acesso a recursos do app
#Usuario pode ser do tipo { MASTER= acesso total, USER= acesso limitado a sua fazenda}

enum UserType {
  MASTER
  DEALER
  ADMIN
  USER
}

type ResponseCreateUser {
  status: String!
  error: String
  user_id: String
}

type ResponseGetUsers {
  status: String!
  error: String
  users: [User!]
}

type ResponseAuthUser {
  status: String!
  error: String
  token: String
}

type User {
  user_id: ID!
  login: String!
  password: String!

  userType: UserType!
}
