input GetFarmsByUserInput {
  user_id: String
}

input DeleteFarmsInput {
  userType: UserType!
  farm_id: String
  user_id: String
}

input UpdateFarmUserData {
  user_id: String!
  userType: UserType!
}

input UpdateFarmDTO {
  farm_id: String!
  farm_name: String!
  farm_city: String!
  farm_lat: Float!
  farm_lng: Float!
}

input RequestUpdateFarmInput {
  user: UpdateFarmUserData!
  farm_id: String!
  newFarm: UpdateFarmDTO!
}

input CreateFarmInput {
  farm_id: String!
  farm_name: String!
  farm_city: String!
  farm_lat: Float!
  farm_lng: Float!
  owner_id: String!
  created_by: String!
  updated_by: String

  admins: [String]
  dealers: [String]
  users: [String]
}

input AddUserInput {
  login: String!
  password: String!
  userType: UserType!
}

input AddUserIntoFarmData {
  add_user: AddUserInput!
  table: TableAddUserIntoFarm!
}

input RequestAddUserIntoFarmInput {
  auth: UpdateFarmUserData!
  farm_id: String!
  data: AddUserIntoFarmData!
}
