type ResponseCreateFarm {
  status: String!
  error: String
  farm_id: String
}

type ResponseFindFarmsByUser {
  status: String!
  error: String
  farms: [Farm]
}

type ResponseDeleteFarms {
  status: String!
  error: String
}

type ResponseUpdateFarm {
  status: String!
  error: String
  farm_id: String
}

type Farm {
  farm_id: String!
  farm_name: String!
  farm_city: String!
  farm_lat: Float!
  farm_lng: Float!
  owner_id: String!
  created_by: String!
  updated_by: String

  admins: [String]
  dealers: [String]
  users: [String]
}
